### ISSUE TITLE
Forcing video stream selection

### ISSUE THREAD

**Issue by igorkulman** [MicrosoftDX/MicrosoftHLSSDK#10]
I have a playlist that contains 1 audio only stream and a few audio+video streams. The automatic stream selection sometimes chooses the audio only stream, because of slow connection I guess. Is there a way to force choosing an audio+video stream? So audio only stream is never chosen?

**Comment by ianisms** [comment]
Take a look at setting starting bitrate and setting bitrate bounds in the developer guide
