### ISSUE TITLE
Repository contains build artifacts

### ISSUE THREAD

**Issue by wagonli** [MicrosoftDX/MicrosoftHLSSDK#3]
The repository contains build artifacts in the following paths

SDK/Windows10/Microsoft.HLSClient/Debug
SDK/Windows10/Microsoft.HLSClient/Release
SDK/Windows10/Microsoft.HLSClient.Setup/obj
SDK/Windows10/Microsoft.HLSClient.Setup/bin

They should not be included in the git repository for obvious reasons.

**Comment by jitghosh** [comment]
Thank you pointing those out. Should be gone now.

-Jit
