### ISSUE TITLE
Microsoft.HLSClient.HLSControllerFactory.HLSControllerReady not firing in UWP app

### ISSUE THREAD

**Issue by JonJam** [MicrosoftDX/MicrosoftHLSSDK#4]
The Microsoft.HLSClient.HLSControllerFactory.HLSControllerReady event is not firing, yet a video begins playing within the Microsoft.PlayerFramework.MediaPlayer.

HLSControllerFactory controllerFactory = new HLSControllerFactory();
HLSControllerFactory controllerFactory.HLSControllerReady += ControllerFactory_HLSControllerReady;

**Comment by jitghosh** [comment]
If you are using the Playerframework plugins for HLS (which it seems you are) then you do not create your own factory – you get the pne that the PF plugin creates for you.

//get the HLS plugin from the PF player
      var hlsplugin = mediaplayer.Plugins.Where(p => p is HLSPlugin).FirstOrDefault();
      //get the controller factory
      _controllerfactory = (hlsplugin as HLSPlugin).ControllerFactory;
      //subscribe to HLSControllerReady
      _controllerfactory.HLSControllerReady += _controllerfactory_HLSControllerReady;

-Jit

**Comment by JonJam** [comment]
Thank you :) that worked a treat.
