### ISSUE TITLE
SDK folder name is too long

### ISSUE THREAD

**Issue by dr-ratio** [MicrosoftDX/MicrosoftHLSSDK#5]
A practice many use to eliminate build system installation dependencies and improve targeted version control is to move SDK References to utilize local paths.  We have done this.  However, it turns out that although everything worked on my end, the build machine and other devs cannot even sync the repo anymore, because of extremely long filenames being used by the HLS plugin.  For example, this was short enough on my machine that I had no idea there would be a problem:

```
C:\Git\[short-solution-name]\libs\Windows\v8.1\ExtensionSDKs\Microsoft Player Framework Adaptive Streaming Plugin for HLS for Windows 8.1 - JS\1.2.0.0\Redist\CommonConfiguration\neutral\Microsoft.PlayerFramework.Js.HLS\js\HLSPlugin.js
```

When a build machine tries to sync it from something like "c:\workspace[build-job-name-here]..." it is suddenly trying to breach the hard Windows filepath limit of ~250 characters and all hell breaks loose.  One attempted fix was to rename "Microsoft Player Framework Adaptive Streaming Plugin for HLS for Windows 8.1 - JS" to something shorter, but then of course we had to adjust the project references to use the hacked name as well, which introduces a pain point for merging future versions.  (Also, git is having issues with the old filename and still won't sync even though we've fixed it, but that's beside the point.)

I'd like if we could noticeably reduce the length of the base SDK folder name to help accommodate local SDK Reference strategies, as the length is just too restrictive as is.

**Comment by ianisms** [comment]
Good points.  We will address this as soon as we can.
