### ISSUE TITLE
MSHLS.PF.Setup.vsix for Windows 8.1.

### ISSUE THREAD

**Issue by dr-ratio** [MicrosoftDX/MicrosoftHLSSDK#7]
Please include an updated, working MSHLS.PF.Setup.vsix for Windows 8.1.

(Would expect to see it at https://github.com/MicrosoftDX/MicrosoftHLSSDK/tree/master/Installers/Windows%208.1)

**Comment by igorkulman** [comment]
I could also use it. Building it from source is not exactly trivial.

**Comment by ianisms** [comment]
https://github.com/MicrosoftDX/MicrosoftHLSSDK/blob/master/Installers/Windows%208.1/MSHLS.PF.Setup.vsix
