### ISSUE TITLE
SDK does not show debug information after enabling Logging

### ISSUE THREAD

**Issue by lionpham** [MicrosoftDX/MicrosoftHLSSDK#8]
Hi,

I followed the BuildInstructions.docx to enable Logging. However, after installed the logging enabled SDK, I could not see any debug information of the SDK in Output window. Do I miss any steps?

Looking for your help.

Regards

**Comment by jitghosh** [comment]
Please make sure that when you debug your app (assuming it is either a C# or WinJS app) you have set the debug mode to mixed – otherwise you will not see the debug log.

-Jit

**Comment by lionpham** [comment]
Thanks for your answer. It worked!
