### ISSUE TITLE
Closed captions do not display with latest MMPPF and HLSSDK

### ISSUE THREAD

**Issue by Miomir** [MicrosoftDX/MicrosoftHLSSDK#9]
Hello, I cannot see closed captions in the HLS video (captions are displayed when the same video is played via mediaElement, instead of MMPPF instance), using latest MMPPF and HLSSDK installers from this forum. All other plugins (e.g. FreeWheel) work, but CC608 does not. Code snippet below, help would be appreciated.

Microsoft.PlayerFramework.MediaPlayer mediaPlayer; 
Microsoft.PlayerFramework.CC608.CC608Plugin cc608Plugin;
Microsoft.PlayerFramework.Advertising.FreeWheelPlugin fwPlugin;

this.mediaPlayer = new Microsoft.PlayerFramework.MediaPlayer();
this.cc608Plugin = new Microsoft.PlayerFramework.CC608.CC608Plugin(); 
this.mediaPlayer.Plugins.Add(cc608Plugin);  
this.fwPlugin = new Microsoft.PlayerFramework.Advertising.FreeWheelPlugin();
string fwUrl = "sample ad URL";
this.fwPlugin.Source = new Uri(fwUrl);
this.mediaPlayer.Plugins.Add(fwPlugin);

playGrid.Children.Add(mediaPlayer);
this.mediaPlayer.Source = new Uri("sample m3u8 media");

**Comment by ianisms** [comment]
Just tested the HLS PF sample from https://github.com/MicrosoftDX/MicrosoftHLSSDK/tree/master/PFPlugins/Windows10/Samples with the latest version of PF (3.0.0.1) using the Apple Advanced Test Stream which has CC608 captions and they show fine.

**Comment by ianisms** [comment]
Does the Apple Advanced Test Stream (http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8) show captions in your player?  If so, there might be an issue with the captions format in your stream or at least how the CC608 plugin is parsing them.  If not, there is something probably awry with your player configuration...

**Comment by Miomir** [comment]
No, Apple Advanced Test Stream doesn't show CC either in my test

My test is very simplistic, just added references and added few code lines as above (FW plugin lines can be comment out), should be easy to reproduce.Which particular project from Samples are you referring to?

I just modified VideoPlayback project from "Samples" and CC do display in mediaElement, but not in mediaPlayer, if I just change single line below:
mediaPlayer.Source = new Uri(myUrl); //Doesn't show CC for any m3u8, otherwise plays OK
mediaElement.Source = new Uri(myUrl); // CC display fine

I didn't build HLS SDK or MMPPF, just used published vsix Installers:
MMPPF size 6833K (from Oct 16th)
Microsoft.HLSClient.Setup.vsix size 7862K (from Sep 2)
MSHLS.PF.Setup.vsix size 3737K (from Sep 2)

Help would be appreciated.

**Comment by ianisms** [comment]
https://github.com/MicrosoftDX/MicrosoftHLSSDK/tree/master/PFPlugins/Windows10/Samples/MSHLS.PF.XAML.Sample

Just remove the old PF reference and add the PF 3.0.0.1 reference.

**Comment by ianisms** [comment]
Does the captions selection button showing for you?  If not you need to set  IsCaptionSelectionEnabled="True" IsCaptionSelectionVisible="True" on the player.

**Comment by ianisms** [comment]
You also need to set the ClosedCaptionType on the HLSPlugin like so:

```
        var hlsPlugin = new Microsoft.PlayerFramework.Adaptive.HLS.HLSPlugin();
        hlsPlugin.ClosedCaptionType = Microsoft.PlayerFramework.Adaptive.HLS.ClosedCaptionType.CC608Instream;
```

**Comment by Miomir** [comment]
I added to following lines to my code mentioned earlier:
            var hlsPlugin = new Microsoft.PlayerFramework.Adaptive.HLS.HLSPlugin();
            hlsPlugin.ClosedCaptionType = Microsoft.PlayerFramework.Adaptive.HLS.ClosedCaptionType.CC608Instream;
            this.mediaPlayer.Plugins.Add(hlsPlugin);

However adding CaptionType didn't help, except that CC1…CC4 sub-options now display upon clicking on CC button, but still no CC verbiage either in Apple’s or our HLS sample. 

It is interesting that, with the same MMPPF code I shared, CC text does show in the original VideoPlayback sample, which is in mkv format (not HLS):
https://mediaplatstorage1.blob.core.windows.net/windows-universal-samples-media/elephantsdream-clip-h264_sd-aac_eng-aac_spa-aac_eng_commentary-srt_eng-srt_por-srt_swe.mkv.

The suggested project (MSHLS.PF.XAML.Sample) is VERY complex, it combines JS and XAML, tries also to fetch some additional VS (extensibility) tools and to build all plugins from source. It doesn't compile for me and troubleshooting this would take much time. I am just trying to have XAML-basd playback in a simplest way possible and my test have less than 10 lines added to VideoPlayback project as described. Could you please try to reproduce or suggest some simpler project.

Thanks

**Comment by ianisms** [comment]
I don't think you are looking at the right sample:  https://github.com/MicrosoftDX/MicrosoftHLSSDK/tree/master/PFPlugins/Windows10/Samples/MSHLS.PF.XAML.Sample , just open the MSHLS.PF.XAML.Sample.csproj file.

Regardless, will take a closer look when possible.

**Comment by ianisms** [comment]
Please make sure you are adding the extensions declaration below to your Package.appxmanifest file in your project.  It should be placed near the end after capabilities.  If you do not, the HLS SDK will not actually be used and the native platform HLS playback capabilities will.  This is covered in section 4 of the developer guide (4. Modifying the app manifest): https://github.com/MicrosoftDX/MicrosoftHLSSDK/blob/master/Microsoft%20HLS%20SDK%20Developer%20Guide%20v1.2.pdf

``` XML
  <Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>Microsoft.HLSClient.dll</Path>
        <ActivatableClass ActivatableClassId="Microsoft.HLSClient.HLSPlaylistHandler" ThreadingModel="both"/>
      </InProcessServer>
    </Extension>
  </Extensions>
```

**Comment by Miomir** [comment]
Thanks, that was that. I didn't think that was still needed in Windows 10 and got confused because everything except CC worked (as opposed to Win 8.1 where HLS video just didn't play without extensions). 
These lines added in Package.appxmanifest (same lin as in Win 8.1) made CC appear:
  <Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>Microsoft.HLSClient.dll</Path>
        <ActivatableClass ActivatableClassId="Microsoft.HLSClient.HLSPlaylistHandler" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
  </Extensions>

**Comment by ianisms** [comment]
Glad it is working

**Comment by Miomir** [comment]
Thanks for your help.
So we should be fine for CC in HLS, a question though is there any sample of the UWP/HLSSDK CC implementation for mp4 clips (probably with external captions)?

**Comment by ianisms** [comment]
No MP4 would not use HLSSDK.  There are samples of using sidecar captions (TTML and WebVTT) with progressive video in the Player Framework samples:  https://playerframework.codeplex.com/downloads/get/1494477

**Comment by Miomir** [comment]
Thanks again. We got basic CC working for both HLS and MP4 now. However, we have an issue porting Caption Settings (used for customization) in the case of CC608. CaptionSettings member doesn't exist anymore under Microsoft.PlayerFramework.CC608, so the line below (which used to work on Windows 8.1) now gives syntax error: "The type or namespace 'CaptionSettings' doesn't exist in namespace Microsoft.PlayerFramework.CC608 (are you missing an assembly reference)?"

Microsoft.PlayerFramework.CC608.CaptionSettings.CC608CaptionSettingsPlugin cc608SettingsPlugin;

Adding reference to MicrosoftPlayerFramwork CaptionSettings Plugin doesn't help. What is changed syntax or (if it is deprecated) how can we do CC customization in Windows 10 (for either CC608 or WebVTT).\?

Thanks. Miomir

**Comment by ianisms** [comment]
Captions settings are now baked into the platform, Settings ==> Ease of Access ==> Closed Captions.
